"""Hyphenation points for the texts of the Start Guide: writes addon/renderbricker/hyphens.py.

The guide's explanations are set as justified text in the sidebar (UPDATES #36). Blender has no hyphenation
dictionary, so the points of every long word are looked up here, once, when the texts change - and stored
as a table the add-on reads. The texts in guide.py stay plain.

    python scripts/docs/hyphenate_guide.py [--check]

--check writes nothing and ends with 1 when the table in hyphens.py is not the one the texts need (a text
was changed and this script not run). Needs: pip install pyphen"""
import ast, os, re, sys

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", ".."))
GUIDE = os.path.join(ROOT, "addon", "renderbricker", "guide.py")
OUT = os.path.join(ROOT, "addon", "renderbricker", "hyphens.py")
MIN_WORD = 6                    # shorter words are never broken
# Names and words the dictionary does not know or breaks badly; "" in front: no break at all.
OWN = {"Mecabricks": "Meca|bricks", "Renderbricker": "Ren|der|bricker", "Renderbricks": "Ren|der|bricks",
       "Jarraud": "Jarraud", "Scrubs": "Scrubs", "Blenders": "Blen|ders", "Blender": "Blen|der",
       "Outliner": "Out|liner", "viewport": "view|port", "Viewport": "View|port", "headless": "head|less",
       "rbcache": "rbcache", "Cycles": "Cycles", "Physical": "Phys|i|cal", "afterwards": "af|ter|wards",
       "Afterwards": "Af|ter|wards", "overwritten": "over|writ|ten", "background": "back|ground",
       "unchanged": "un|changed", "rendering": "ren|der|ing", "rendered": "ren|dered", "elevation": "el|e|va|tion",
       "Transparent": "Trans|par|ent", "Resolution": "Res|o|lu|tion", "smoothed": "smoothed", "changed": "changed",
       "pressed": "pressed", "marked": "marked", "listed": "listed", "shapes": "shapes", "frames": "frames",
       "broken": "bro|ken", "folded": "fold|ed", "imported": "im|port|ed", "selected": "se|lect|ed",
       "Selected": "Se|lect|ed", "converted": "con|vert|ed", "stored": "stored", "decides": "de|cides",
       "copies": "cop|ies", "process": "proc|ess", "processes": "proc|ess|es", "processor": "proc|es|sor"}


def guide_texts():
    """Every explanation string of guide.GUIDE (read from the source: guide.py imports bpy)."""
    tree = ast.parse(open(GUIDE, encoding="utf-8").read())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(getattr(t, "id", None) == "GUIDE" for t in node.targets):
            return [c.value for c in ast.walk(node.value) if isinstance(c, ast.Constant) and isinstance(c.value, str)]
    raise SystemExit("GUIDE not found in guide.py")


def table():
    import pyphen
    dic = pyphen.Pyphen(lang="en_US")
    words = sorted({w for t in guide_texts() for w in re.findall(r"[A-Za-z]{%d,}" % MIN_WORD, t)})
    return {w: OWN.get(w) or dic.inserted(w, hyphen="|") for w in words}


def source(tab):
    lines = ['"""Hyphenation points of the long words in the Start Guide\'s texts ("|" where a word may break).',
             "",
             "Generated by scripts/docs/hyphenate_guide.py from guide.GUIDE - do not edit by hand: change the text or",
             'the list OWN in that script and run it again (python scripts/docs/hyphenate_guide.py)."""',
             f"MIN_WORD = {MIN_WORD}                    # shorter words are never broken",
             "",
             "",
             "TABLE = {"]
    lines += [f'    "{w}": "{v}",' for w, v in tab.items()]
    lines += ["}", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    text = source(table())
    if "--check" in sys.argv:
        same = os.path.isfile(OUT) and open(OUT, encoding="utf-8").read() == text
        print("hyphens.py is up to date" if same else "hyphens.py is NOT up to date - run scripts/docs/hyphenate_guide.py")
        sys.exit(0 if same else 1)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    tab = table()
    print(f"{OUT}: {len(tab)} words, {sum(1 for v in tab.values() if '|' in v)} with points")
